version: "3"

services:
    # mysql-db:
    #     image: mysql:5.7
    #     restart: always
    #     environment:
    #         MYSQL_DATABASE: 'AA_AUDT'
    #         # So you don't have to use root, but you can if you like
    #         MYSQL_USER: 'user'
    #         # You can use whatever password you like
    #         MYSQL_PASSWORD: 'password'
    #         # Password for root access
    #         MYSQL_ROOT_PASSWORD: 'password'
    #     ports:
    #         # <Port exposed> : < MySQL Port running inside container>
    #         - '3306:3306'
    #     expose:
    #         # Opens port 3306 on the container
    #         - '3306'
    #         # Where our data will be persisted
    #     volumes:
    #         - ./my-mysql/sql-scripts:/docker-entrypoint-initdb.d/:ro
    #         - db_data:/var/lib/mysql
    #     networks: 
    #         - backend_network
    db:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: 'AA_AUDIT'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        volumes:
            - ./mysql-db/sql-scripts:/docker-entrypoint-initdb.d/:ro
            - db_data:/var/lib/mysql
        networks: 
            - backend_network
    
    webapp-backend:
        build: ./webapp-backend
        image: webapp-backend
        volumes:
            - ./webapp-backend/src:/app
        ports: 
            - "5000:5000"
        networks:
            - frontend_network
            - backend_network
        depends_on:
            - db

    # webapp-frontend:
    #     build: ./webapp-frontend
    #     image: webapp-frontend
    #     ports: 
    #         - "5000:5001"
    #     networks:
    #         - frontend_network
    #     depends_on:
    #         - webapp-backend
    
    lab:
        image: jupyter/scipy-notebook
        volumes:
            - ./notebooks/:/notebooks
        ports:
            - "8888:8888"
        environment:
            - JUPYTER_ENABLE_LAB=1
        command: start-notebook.sh --NotebookApp.notebook_dir=/notebooks
        networks:
            - backend_network
            - analysis_network
        depends_on:
            - db

volumes:
    db_data:
    backend_data:

networks:
    frontend_network:
    backend_network:
    analysis_network: 