version: "3"

services:
    db:
        image: mysql
        restart: always
        container_name: db
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: 'AA_AUDIT'
            restart: always
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        volumes:
            - ./mysql-db/sql-scripts:/docker-entrypoint-initdb.d/:ro
            - db_data:/var/lib/mysql
        networks: 
            - backend_network

    webapp-backend:
        build: ./webapp-backend
        restart: always
        container_name: webapp-backend
        volumes:
            - ./webapp-backend/app:/app
        ports: 
            - "5000:5000"
        networks:
            - frontend_network
            - backend_network
        depends_on:
            - db

    # webapp-frontend:
    #     build: ./webapp-frontend
    #     image: webapp-frontend
    #     ports: 
    #         - "5000:5001"
    #     networks:
    #         - frontend_network
    #     depends_on:
    #         - webapp-backend
    
    jupyterhub:
        build: ./jupyterhub
        image: jupyterhub
        restart: always
        container_name: jupyterhub-container
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - jupyterhub_data:/srv/jupyterhub
        ports:
            - "8000:8000"
        environment:
            DOCKER_JUPYTER_CONTAINER: jupyter-notebook
            DOCKER_JUPYTER_IMAGE: scipy-notebook
            DOCKER_NETWORK_NAME: analysis_network
            HUB_IP: jupyterhub
            DOCKER_NOTEBOOK_DIR: ./notebooks 
        # command: start-notebook.sh --NotebookApp.notebook_dir=/notebooks   
        depends_on:
            - db

volumes:
    db_data:
    jupyterhub_data:
       
networks:
    frontend_network:
    backend_network:
    analysis_network: 