-- db name
use AA_AUDIT;

CREATE TABLE input_table (
  name VARCHAR(20),
  color VARCHAR(10)
);

INSERT INTO input_table
  (name, color)
VALUES
  ('Sam', 'blue'),
  ('Ari', 'yellow');


-- MySQL Script generated by MySQL Workbench
-- Wed Sep 16 13:37:30 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AA_AUDIT
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AA_AUDIT
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AA_AUDIT` DEFAULT CHARACTER SET utf8 ;
USE `AA_AUDIT` ;

-- -----------------------------------------------------
-- Table `AA_AUDIT`.`facility_operator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AA_AUDIT`.`facility_operator` ;

CREATE TABLE IF NOT EXISTS `AA_AUDIT`.`facility_operator` (
  `operator_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `registration_number` VARCHAR(45) NULL,
  `public_private` VARCHAR(45) NULL,
  PRIMARY KEY (`operator_id`),
  UNIQUE INDEX `registration_number_UNIQUE` (`registration_number` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AA_AUDIT`.`facilities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AA_AUDIT`.`facilities` ;

CREATE TABLE IF NOT EXISTS `AA_AUDIT`.`facilities` (
  `facility_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `facility_operator_operator_id` INT NOT NULL,
  PRIMARY KEY (`facility_id`, `facility_operator_operator_id`),
  INDEX `fk_facilities_facility_operator1_idx` (`facility_operator_operator_id` ASC) VISIBLE,
  CONSTRAINT `fk_facilities_facility_operator1`
    FOREIGN KEY (`facility_operator_operator_id`)
    REFERENCES `AA_AUDIT`.`facility_operator` (`operator_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AA_AUDIT`.`versions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AA_AUDIT`.`versions` ;

CREATE TABLE IF NOT EXISTS `AA_AUDIT`.`versions` (
  `version` INT NOT NULL,
  `date_created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `comments` BLOB NULL,
  PRIMARY KEY (`version`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AA_AUDIT`.`audits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AA_AUDIT`.`audits` ;

CREATE TABLE IF NOT EXISTS `AA_AUDIT`.`audits` (
  `audit_id` INT NOT NULL,
  `audit_date` DATETIME NULL,
  `revision_num` VARCHAR(45) NOT NULL,
  `facilities_facility_id` INT NOT NULL,
  `versions_version` INT NOT NULL,
  PRIMARY KEY (`audit_id`, `revision_num`, `facilities_facility_id`, `versions_version`),
  INDEX `fk_audits_facilities1_idx` (`facilities_facility_id` ASC) VISIBLE,
  INDEX `fk_audits_versions1_idx` (`versions_version` ASC) VISIBLE,
  CONSTRAINT `fk_audits_facilities1`
    FOREIGN KEY (`facilities_facility_id`)
    REFERENCES `AA_AUDIT`.`facilities` (`facility_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_audits_versions1`
    FOREIGN KEY (`versions_version`)
    REFERENCES `AA_AUDIT`.`versions` (`version`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AA_AUDIT`.`auditors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AA_AUDIT`.`auditors` ;

CREATE TABLE IF NOT EXISTS `AA_AUDIT`.`auditors` (
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `employee_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`employee_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AA_AUDIT`.`reports`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AA_AUDIT`.`reports` ;

CREATE TABLE IF NOT EXISTS `AA_AUDIT`.`reports` (
  `report_id` INT NOT NULL,
  `reporting_date` DATETIME NULL,
  `report_document` VARCHAR(45) NULL,
  PRIMARY KEY (`report_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AA_AUDIT`.`linac_models`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AA_AUDIT`.`linac_models` ;

CREATE TABLE IF NOT EXISTS `AA_AUDIT`.`linac_models` (
  `linac_model_id` INT NOT NULL,
  `manufacturer` VARCHAR(45) NULL,
  `model` VARCHAR(45) NULL,
  PRIMARY KEY (`linac_model_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AA_AUDIT`.`planning_systems`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AA_AUDIT`.`planning_systems` ;

CREATE TABLE IF NOT EXISTS `AA_AUDIT`.`planning_systems` (
  `ps_id` INT NOT NULL,
  `manufacturor` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `version` VARCHAR(45) NULL,
  `algorithm` VARCHAR(45) NULL,
  PRIMARY KEY (`ps_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AA_AUDIT`.`phantoms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AA_AUDIT`.`phantoms` ;

CREATE TABLE IF NOT EXISTS `AA_AUDIT`.`phantoms` (
  `phantom_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`phantom_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AA_AUDIT`.`audits_has_auditors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AA_AUDIT`.`audits_has_auditors` ;

CREATE TABLE IF NOT EXISTS `AA_AUDIT`.`audits_has_auditors` (
  `audits_audit_id` INT NOT NULL,
  `audits_facilities_facility_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`audits_audit_id`, `audits_facilities_facility_id`),
  INDEX `fk_audits_has_auditors_auditors1_idx` (`audits_facilities_facility_id` ASC) VISIBLE,
  INDEX `fk_audits_has_auditors_audits1_idx` (`audits_audit_id` ASC) VISIBLE,
  CONSTRAINT `fk_audits_has_auditors_audits1`
    FOREIGN KEY (`audits_audit_id`)
    REFERENCES `AA_AUDIT`.`audits` (`audit_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_audits_has_auditors_auditors1`
    FOREIGN KEY (`audits_facilities_facility_id`)
    REFERENCES `AA_AUDIT`.`auditors` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AA_AUDIT`.`audits_has_reports`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AA_AUDIT`.`audits_has_reports` ;

CREATE TABLE IF NOT EXISTS `AA_AUDIT`.`audits_has_reports` (
  `audits_audit_id` INT NOT NULL,
  `reports_report_id` INT NOT NULL,
  PRIMARY KEY (`audits_audit_id`, `reports_report_id`),
  INDEX `fk_audits_has_reports_reports1_idx` (`reports_report_id` ASC) VISIBLE,
  INDEX `fk_audits_has_reports_audits1_idx` (`audits_audit_id` ASC) VISIBLE,
  CONSTRAINT `fk_audits_has_reports_audits1`
    FOREIGN KEY (`audits_audit_id`)
    REFERENCES `AA_AUDIT`.`audits` (`audit_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_audits_has_reports_reports1`
    FOREIGN KEY (`reports_report_id`)
    REFERENCES `AA_AUDIT`.`reports` (`report_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AA_AUDIT`.`energy_levels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AA_AUDIT`.`energy_levels` ;

CREATE TABLE IF NOT EXISTS `AA_AUDIT`.`energy_levels` (
  `energy_level` INT NOT NULL,
  PRIMARY KEY (`energy_level`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AA_AUDIT`.`cases`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AA_AUDIT`.`cases` ;

CREATE TABLE IF NOT EXISTS `AA_AUDIT`.`cases` (
  `case_id` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`case_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AA_AUDIT`.`beams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AA_AUDIT`.`beams` ;

CREATE TABLE IF NOT EXISTS `AA_AUDIT`.`beams` (
  `beam_id` INT NOT NULL,
  `descriptiotn` VARCHAR(45) NULL,
  `direction` VARCHAR(45) NULL,
  PRIMARY KEY (`beam_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AA_AUDIT`.`points`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AA_AUDIT`.`points` ;

CREATE TABLE IF NOT EXISTS `AA_AUDIT`.`points` (
  `point` INT NOT NULL,
  `position` VARCHAR(45) NULL,
  PRIMARY KEY (`point`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AA_AUDIT`.`facilities_has_linacs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AA_AUDIT`.`facilities_has_linacs` ;

CREATE TABLE IF NOT EXISTS `AA_AUDIT`.`facilities_has_linacs` (
  `facilities_facility_id` INT NOT NULL,
  `linacs_linac_model_id` INT NOT NULL,
  `linac_serial_number` VARCHAR(45) NULL,
  `linac_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`linac_id`, `linacs_linac_model_id`, `facilities_facility_id`),
  INDEX `fk_facilities_has_linacs_linacs1_idx` (`linacs_linac_model_id` ASC) VISIBLE,
  INDEX `fk_facilities_has_linacs_facilities1_idx` (`facilities_facility_id` ASC) VISIBLE,
  CONSTRAINT `fk_facilities_has_linacs_facilities1`
    FOREIGN KEY (`facilities_facility_id`)
    REFERENCES `AA_AUDIT`.`facilities` (`facility_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_facilities_has_linacs_linacs1`
    FOREIGN KEY (`linacs_linac_model_id`)
    REFERENCES `AA_AUDIT`.`linac_models` (`linac_model_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AA_AUDIT`.`ct_models`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AA_AUDIT`.`ct_models` ;

CREATE TABLE IF NOT EXISTS `AA_AUDIT`.`ct_models` (
  `ct_model_id` INT NOT NULL,
  `manufacturer` VARCHAR(45) NULL,
  `model` VARCHAR(45) NULL,
  PRIMARY KEY (`ct_model_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AA_AUDIT`.`facilities_has_cts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AA_AUDIT`.`facilities_has_cts` ;

CREATE TABLE IF NOT EXISTS `AA_AUDIT`.`facilities_has_cts` (
  `facilities_facility_operator_operator_id` INT NOT NULL,
  `ct_models_ct_model_id` INT NOT NULL,
  `ct_id` VARCHAR(45) NOT NULL,
  `ct_models_ct_model_id1` INT NOT NULL,
  `facilities_facility_id` INT NOT NULL,
  `facilities_facility_operator_operator_id1` INT NOT NULL,
  PRIMARY KEY (`ct_id`, `ct_models_ct_model_id1`, `facilities_facility_id`, `facilities_facility_operator_operator_id1`),
  INDEX `fk_facilities_has_cts_ct_models1_idx` (`ct_models_ct_model_id1` ASC) VISIBLE,
  INDEX `fk_facilities_has_cts_facilities1_idx` (`facilities_facility_id` ASC, `facilities_facility_operator_operator_id1` ASC) VISIBLE,
  CONSTRAINT `fk_facilities_has_cts_ct_models1`
    FOREIGN KEY (`ct_models_ct_model_id1`)
    REFERENCES `AA_AUDIT`.`ct_models` (`ct_model_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_facilities_has_cts_facilities1`
    FOREIGN KEY (`facilities_facility_id` , `facilities_facility_operator_operator_id1`)
    REFERENCES `AA_AUDIT`.`facilities` (`facility_id` , `facility_operator_operator_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AA_AUDIT`.`facilities_has_planning_systems`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AA_AUDIT`.`facilities_has_planning_systems` ;

CREATE TABLE IF NOT EXISTS `AA_AUDIT`.`facilities_has_planning_systems` (
  `facilities_facility_id` INT NOT NULL,
  `planning_systems_ps_id` INT NOT NULL,
  `planning_system_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`facilities_facility_id`, `planning_systems_ps_id`, `planning_system_id`),
  INDEX `fk_facilities_has_planning_systems_planning_systems1_idx` (`planning_systems_ps_id` ASC) VISIBLE,
  INDEX `fk_facilities_has_planning_systems_facilities1_idx` (`facilities_facility_id` ASC) VISIBLE,
  CONSTRAINT `fk_facilities_has_planning_systems_facilities1`
    FOREIGN KEY (`facilities_facility_id`)
    REFERENCES `AA_AUDIT`.`facilities` (`facility_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_facilities_has_planning_systems_planning_systems1`
    FOREIGN KEY (`planning_systems_ps_id`)
    REFERENCES `AA_AUDIT`.`planning_systems` (`ps_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AA_AUDIT`.`results`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AA_AUDIT`.`results` ;

CREATE TABLE IF NOT EXISTS `AA_AUDIT`.`results` (
  `result_id` INT NOT NULL,
  `energy_levels_energy_level` INT NOT NULL,
  `points_point` INT NOT NULL,
  `beams_beam_id` INT NOT NULL,
  `cases_case_id` INT NOT NULL,
  `phantoms_phantom_id` INT NOT NULL,
  `facilities_has_linacs_linac_id` VARCHAR(45) NOT NULL,
  `measured_current` VARCHAR(45) NULL,
  `audits_audit_id` INT NOT NULL,
  `audits_revision_num` VARCHAR(45) NOT NULL,
  `predicted_current` VARCHAR(45) NULL,
  `facilities_has_cts_ct_id` VARCHAR(45) NOT NULL,
  `facilities_has_planning_systems_facilities_facility_id` INT NOT NULL,
  `facilities_has_planning_systems_planning_systems_ps_id` INT NOT NULL,
  `facilities_has_planning_systems_planning_system_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`result_id`, `energy_levels_energy_level`, `points_point`, `beams_beam_id`, `cases_case_id`, `facilities_has_linacs_linac_id`, `audits_audit_id`, `audits_revision_num`, `facilities_has_cts_ct_id`, `phantoms_phantom_id`, `facilities_has_planning_systems_facilities_facility_id`, `facilities_has_planning_systems_planning_systems_ps_id`, `facilities_has_planning_systems_planning_system_id`),
  INDEX `fk_results_energy_levels1_idx` (`energy_levels_energy_level` ASC) VISIBLE,
  INDEX `fk_results_points1_idx` (`points_point` ASC) VISIBLE,
  INDEX `fk_results_beams1_idx` (`beams_beam_id` ASC) VISIBLE,
  INDEX `fk_results_cases1_idx` (`cases_case_id` ASC) VISIBLE,
  INDEX `fk_results_phantoms1_idx` (`phantoms_phantom_id` ASC) VISIBLE,
  INDEX `fk_results_facilities_has_linacs1_idx` (`facilities_has_linacs_linac_id` ASC) VISIBLE,
  INDEX `fk_results_audits1_idx` (`audits_audit_id` ASC, `audits_revision_num` ASC) VISIBLE,
  INDEX `fk_results_facilities_has_cts1_idx` (`facilities_has_cts_ct_id` ASC) VISIBLE,
  INDEX `fk_results_facilities_has_planning_systems1_idx` (`facilities_has_planning_systems_facilities_facility_id` ASC, `facilities_has_planning_systems_planning_systems_ps_id` ASC, `facilities_has_planning_systems_planning_system_id` ASC) VISIBLE,
  CONSTRAINT `fk_results_energy_levels1`
    FOREIGN KEY (`energy_levels_energy_level`)
    REFERENCES `AA_AUDIT`.`energy_levels` (`energy_level`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_results_points1`
    FOREIGN KEY (`points_point`)
    REFERENCES `AA_AUDIT`.`points` (`point`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_results_beams1`
    FOREIGN KEY (`beams_beam_id`)
    REFERENCES `AA_AUDIT`.`beams` (`beam_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_results_cases1`
    FOREIGN KEY (`cases_case_id`)
    REFERENCES `AA_AUDIT`.`cases` (`case_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_results_phantoms1`
    FOREIGN KEY (`phantoms_phantom_id`)
    REFERENCES `AA_AUDIT`.`phantoms` (`phantom_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_results_facilities_has_linacs1`
    FOREIGN KEY (`facilities_has_linacs_linac_id`)
    REFERENCES `AA_AUDIT`.`facilities_has_linacs` (`linac_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_results_audits1`
    FOREIGN KEY (`audits_audit_id` , `audits_revision_num`)
    REFERENCES `AA_AUDIT`.`audits` (`audit_id` , `revision_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_results_facilities_has_cts1`
    FOREIGN KEY (`facilities_has_cts_ct_id`)
    REFERENCES `AA_AUDIT`.`facilities_has_cts` (`ct_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_results_facilities_has_planning_systems1`
    FOREIGN KEY (`facilities_has_planning_systems_facilities_facility_id` , `facilities_has_planning_systems_planning_systems_ps_id` , `facilities_has_planning_systems_planning_system_id`)
    REFERENCES `AA_AUDIT`.`facilities_has_planning_systems` (`facilities_facility_id` , `planning_systems_ps_id` , `planning_system_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AA_AUDIT`.`trs_398_method`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AA_AUDIT`.`trs_398_method` ;

CREATE TABLE IF NOT EXISTS `AA_AUDIT`.`trs_398_method` (
  `method_id` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`method_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AA_AUDIT`.`facility_stated`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AA_AUDIT`.`facility_stated` ;

CREATE TABLE IF NOT EXISTS `AA_AUDIT`.`facility_stated` (
  `audits_audit_id` INT NOT NULL,
  `facilities_has_linacs_linac_id` VARCHAR(45) NOT NULL,
  `facilities_facility_id` INT NOT NULL,
  `energy_levels_energy_level` INT NOT NULL,
  `trs_398_method_method_id` INT NOT NULL,
  `dose` VARCHAR(45) NULL,
  `facilities_has_planning_systems_facilities_facility_id` INT NOT NULL,
  `facilities_has_planning_systems_planning_systems_ps_id` INT NOT NULL,
  `facilities_has_planning_systems_planning_system_id` VARCHAR(45) NOT NULL,
  `facilities_has_cts_facilities_facility_id` INT NOT NULL,
  `facilities_has_cts_ct_id` VARCHAR(45) NOT NULL,
  `facilities_has_cts_ct_models_ct_model_id1` INT NOT NULL,
  `facilities_has_cts_facilities_facility_id1` INT NOT NULL,
  `facilities_has_cts_facilities_facility_operator_operator_id1` INT NOT NULL,
  PRIMARY KEY (`audits_audit_id`, `facilities_has_linacs_linac_id`, `facilities_facility_id`, `energy_levels_energy_level`, `trs_398_method_method_id`, `facilities_has_planning_systems_facilities_facility_id`, `facilities_has_planning_systems_planning_systems_ps_id`, `facilities_has_planning_systems_planning_system_id`, `facilities_has_cts_facilities_facility_id`, `facilities_has_cts_ct_id`, `facilities_has_cts_ct_models_ct_model_id1`, `facilities_has_cts_facilities_facility_id1`, `facilities_has_cts_facilities_facility_operator_operator_id1`),
  INDEX `fk_facility_stated_rename_facilities_has_linacs1_idx` (`facilities_has_linacs_linac_id` ASC) VISIBLE,
  INDEX `fk_facility_stated_rename_facilities1_idx` (`facilities_facility_id` ASC) VISIBLE,
  INDEX `fk_facility_stated_rename_energy_levels1_idx` (`energy_levels_energy_level` ASC) VISIBLE,
  INDEX `fk_facility_stated_rename_trs_398_method1_idx` (`trs_398_method_method_id` ASC) VISIBLE,
  INDEX `fk_facility_stated_facilities_has_planning_systems1_idx` (`facilities_has_planning_systems_facilities_facility_id` ASC, `facilities_has_planning_systems_planning_systems_ps_id` ASC, `facilities_has_planning_systems_planning_system_id` ASC) VISIBLE,
  INDEX `fk_facility_stated_facilities_has_cts1_idx` (`facilities_has_cts_ct_id` ASC, `facilities_has_cts_ct_models_ct_model_id1` ASC, `facilities_has_cts_facilities_facility_id1` ASC, `facilities_has_cts_facilities_facility_operator_operator_id1` ASC) VISIBLE,
  CONSTRAINT `fk_facility_stated_rename_audits1`
    FOREIGN KEY (`audits_audit_id`)
    REFERENCES `AA_AUDIT`.`audits` (`audit_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_facility_stated_rename_facilities_has_linacs1`
    FOREIGN KEY (`facilities_has_linacs_linac_id`)
    REFERENCES `AA_AUDIT`.`facilities_has_linacs` (`linac_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_facility_stated_rename_facilities1`
    FOREIGN KEY (`facilities_facility_id`)
    REFERENCES `AA_AUDIT`.`facilities` (`facility_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_facility_stated_rename_energy_levels1`
    FOREIGN KEY (`energy_levels_energy_level`)
    REFERENCES `AA_AUDIT`.`energy_levels` (`energy_level`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_facility_stated_rename_trs_398_method1`
    FOREIGN KEY (`trs_398_method_method_id`)
    REFERENCES `AA_AUDIT`.`trs_398_method` (`method_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_facility_stated_facilities_has_planning_systems1`
    FOREIGN KEY (`facilities_has_planning_systems_facilities_facility_id` , `facilities_has_planning_systems_planning_systems_ps_id` , `facilities_has_planning_systems_planning_system_id`)
    REFERENCES `AA_AUDIT`.`facilities_has_planning_systems` (`facilities_facility_id` , `planning_systems_ps_id` , `planning_system_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_facility_stated_facilities_has_cts1`
    FOREIGN KEY (`facilities_has_cts_ct_id` , `facilities_has_cts_ct_models_ct_model_id1` , `facilities_has_cts_facilities_facility_id1` , `facilities_has_cts_facilities_facility_operator_operator_id1`)
    REFERENCES `AA_AUDIT`.`facilities_has_cts` (`ct_id` , `ct_models_ct_model_id1` , `facilities_facility_id` , `facilities_facility_operator_operator_id1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AA_AUDIT`.`constant_values`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AA_AUDIT`.`constant_values` ;

CREATE TABLE IF NOT EXISTS `AA_AUDIT`.`constant_values` (
  `constant_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `value` JSON NULL,
  `date_inserted` DATETIME NULL,
  `versions_version` INT NOT NULL,
  PRIMARY KEY (`constant_id`, `versions_version`),
  INDEX `fk_constant_values_versions1_idx` (`versions_version` ASC) VISIBLE,
  CONSTRAINT `fk_constant_values_versions1`
    FOREIGN KEY (`versions_version`)
    REFERENCES `AA_AUDIT`.`versions` (`version`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;